project:
  type: website

website:
  page-navigation: true
  title: "The Strain on Scientific Publishing"
  description: "Home page for the paper 'The Strain on Scientific Publishing' by Mark A Hanson, Dan Brockington, Paolo Crosetto and Pablo Gomez Barreiro"
  site-url: "https://the-strain-on-scientific-publishing.github.io/website/"
  site-path: "/"
  twitter-card:
    creator: "@paolocrosetto"
    image: images/abstract.jpeg
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2023, Paolo Crosetto"
    background: "#D9E3E4"
    
  sidebar:
    background: "#D9E3E4"
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/the-strain-on-scientific-publishing
        text: "GitHub pages for the project"
        target: "_blank"
      - icon: people-fill
        href: about.qmd
        text: "About the team"
      - icon: file-pdf-fill
        href: https://direct.mit.edu/qss/article/doi/10.1162/qss_a_00327/124269/The-strain-on-scientific-publishing 
        text: "The paper on Quantitative Science Studies"
        target: "_blank"
        
    style: "docked"
    search: false
    collapse-level: 0
    contents:
      - href: index.qmd
        text: "Home"
      - href: https://direct.mit.edu/qss/article/doi/10.1162/qss_a_00327/124269/The-strain-on-scientific-publishing 
        text: "Get the paper!"
        target: "_blank"
      - href: https://figshare.com/articles/figure/The_strain_on_scientific_publishing_figures_/24203790
        text: "Plots & Tables (Figshare)"
        target: "_blank"
      - href: about.qmd
        text: "About the authors"
      - href: in-the-press.qmd
        text: "Mentions & articles"
      - href: media.qmd
        text: "Videos & audios"
      - href: presentation.qmd
        text: "Slide decks"
      - href: post.qmd
        text: "The Daily Strain"
      - href: https://pagoba.shinyapps.io/strain_explorer/
        text: "The Strain Explorer (beta app)"
        target: "_blank"
    
format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    toc: true

editor: visual

execute:
  freeze: auto

