project:
  type: website

website:
  page-navigation: true
  title: "The Strain on Scientific Publishing"
  description: "Home page for the paper 'The Strain on Scientific Publishing' by Mark A Hanson, Dan Brockington, Paolo Crosetto and Pablo Gomez Barreiro"
  site-path: "/"
  twitter-card:
    creator: "@paolocrosetto"
    image: images/abstract.jpeg
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2023, Paolo Crosetto"
    background: "#D9E3E4"
    
  sidebar:
    background: "#D9E3E4"
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/the-strain-on-scientific-publishing
        text: "GitHub pages for the project"
        target: "_blank"
      - icon: people-fill
        href: about.qmd
        text: "About the team"
      - icon: file-pdf-fill
        href: https://arxiv.org/abs/2309.15884 
        text: "The paper on ArXiV"
        target: "_blank"
        
    style: "docked"
    search: false
    collapse-level: 0
    contents:
      - href: index.qmd
        text: "Home"
      - href: https://arxiv.org/abs/2309.15884
        text: "Get the paper!"
        target: "_blank"
      - href: https://figshare.com/articles/figure/The_strain_on_scientific_publishing_figures_/24203790
        text: "Plots and Tables (on fighsare)"
        target: "_blank"
      - href: data-and-code.qmd
        text: "Data and Code (forthcoming)"
      - href: about.qmd
        text: "About the authors"
      - href: in-the-press.qmd
        text: "Mentions and articles"
      - href: media.qmd
        text: "Videos and audios"
      - href: presentation.qmd
        text: "Slide decks"
    
format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    toc: true

editor: visual

execute:
  freeze: auto

