---
title: "Articles, threads, posts... about our paper"
---

# Altmetric

```{=html}
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div class="altmetric-embed" data-badge-type="medium-donut" data-badge-details='right' data-altmetric-id="154736608"></div>
```
# Twitter + Mastodon threads

-   [Mastodon thread](https://t.co/pL6Hwl9mnk) by Mark A Hanson
-   [Twitter thread](https://x.com/pagomba/status/1709835364301443388?s=20) by Pablo Gómez Barreiro
-   [Twitter thread](https://twitter.com/PaoloCrosetto/status/1707771226947469471) by Paolo Crosetto
-   [Twitter thread](https://twitter.com/danbrockington/status/1707737121228820523) by Dan Brockington
-   [Twitter thread](https://x.com/eggersnsf/status/1708458262717239692?s=20) by Matthias Egger
-   [Twitter thread](https://x.com/Andrew_Akbashev/status/1725523799959871816?s=20) by Andrew Akbashev
-   [BlueSky thread](https://bsky.app/profile/marcveld.bsky.social/post/3keiaui65s225) by Marc Veldohen

# Press

### English

-   [**Press release**](https://news.exeter.ac.uk/faculty-of-environment-science-and-economy/avalanche-of-papers-could-erode-trust-in-science/) - University of Exeter
-   [**Science \[EN\]**](https://www.science.org/content/article/scienceadviser-scientists-are-publishing-too-many-papers-and-s-bad-science) - Scienceadviser 16 november 2023
-   [**El País \[EN\]**](https://english.elpais.com/science-tech/2023-10-31/public-funds-being-swallowed-up-by-scientific-journals-with-dubious-articles.html) - *Public funds being swallowed up by scientific journals with dubious articles*
-   [**Financial Times \[EN\]**](www.ft.com/content/575f72a8-4eb2-4538-87a8-7652d67d499e#selection-1573.0-1573.65)- *How academic publishers profit from the publish-or-perish culture*
-   [**Newswise \[EN\]**](https://www.newswise.com/articles/avalanche-of-papers-could-erode-trust-in-science) - *Avalanche of papers could erode trust in science*
-   [**Phys.org \[EN\]**](https://phys.org/news/2023-11-avalanche-published-academic-articles-erode.html) - *Avalanche of published academic articles could erode trust in science*
-   [**India Education Diary \[EN\]**](https://indiaeducationdiary.in/the-potential-avalanche-of-papers-a-concern-for-trust-in-science/#google_vignette) **-** *The Potential Avalanche of Papers: A Concern for Trust in Science*
-   [**Paudal \[EN\]**](https://indiaeducationdiary.in/the-potential-avalanche-of-papers-a-concern-for-trust-in-science/#google_vignette "https://www.paudal.com/2023/11/03/the-avalanche-of-articles-can-undermine-trust-in-science-warns-a-study/") - *The "avalanche" of articles can undermine trust in science, warns a study*
-   [**Wall Street Journal \[EN\]**](https://www.wsj.com/science/whats-wrong-with-peer-review-e5d2d428) - *What's Wrong With Peer Review?*
-   [**Brisbane Times \[EN\]**](https://www.brisbanetimes.com.au/national/we-ve-hit-peak-science-and-that-s-not-good-20240116-p5exkb.html) - *We've hit peak science, and that's not good*
-   [**Sidney Morning Herlad \[EN\]**](https://www.msn.com/en-au/news/australia/we-ve-hit-peak-science-and-that-s-not-good/ar-AA1n2LpP) - *We've hit peak science, and that's not good*
-   [**Chemical & Engineering News \[EN\]**](https://cen.acs.org/policy/publishing/academic-social-networking-site-ResearchGate/102/i2) - *Is the academic social networking site ResearchGate still relevant?*
-   [**The Citizen -- Tanzania \[EN\]**](https://www.thecitizen.co.tz/tanzania/news/national/mushrooming-academic-papers-researchers-concern-about-scientific-trust-4512832) - *Mushrooming academic papers: Researchers' concern about scientific trust*
-   [**Swissinfo.ch -- Switzerland \[EN\]**](https://www.swissinfo.ch/eng/science/wrong-ai-generated-images-in-scientific-journal-put-a-strain-on-swiss-publisher-frontiers/73657004) - *AI-generated rat genitalia: Swiss publisher of scientific journal under pressure*


### French

-   [**Actualité web \[FR\]**](https://www.inrae.fr/actualites/ledition-scientifique-pression) on the INRAE website
-   [**L'Express \[FR\]**](https://www.lexpress.fr/sciences-sante/sciences/articles-frauduleux-comment-des-dizaines-de-revues-scientifiques-ont-ete-detournees-YSAUA44SFVEWZKCOJDFO5SKSUI/?utm_medium=Social&utm_source=Twitter&s=09#Echobox=1702965183-1) - article by Antoine Beau on the Hindawi crisis and shutdown

### Spanish

-   [**Press release \[ES\]**](https://www.uab.cat/web/sala-de-premsa-icta-uab/detall-noticia/la-avalancha-de-articulos-podria-socavar-la-confianza-en-la-ciencia-1345819907210.html?detid=1345899419174) - Universitat Autònoma de Barcelona
-   [**El País \[ES\]**](https://elpais.com/ciencia/2023-10-31/la-burbuja-de-las-revistas-cientificas-se-traga-millones-de-euros-de-dinero-publico.html) - *La burbuja de las revistas científicas se traga millones de euros de dinero público*
-   [**El País \[ES\]**](https://elpais.com/opinion/2023-11-06/virus-en-la-publicacion-cientifica.html) - *Virus en la publicación científica*
-   [**La Vanguardia \[ES\]**](https://www.lavanguardia.com/vida/20231103/9350563/avalancha-articulos-socavar-confianza-ciencia-alerta-estudio-agenciaslv20231103.html) **\| [Agencia EFE \[ES\]](https://efs.efeservicios.com/texto/avalancha-articulos-socavar-confianza-ciencia-alerta-estudio/55012231151)** **\| [Infobae \[ES\]](https://www.infobae.com/espana/agencias/2023/11/03/la-avalancha-de-articulos-puede-socavar-la-confianza-en-la-ciencia-alerta-un-estudio/)** **\| [Yahoo \[ES\]](https://es-us.finanzas.yahoo.com/noticias/avalancha-art%C3%ADculos-socavar-confianza-ciencia-123019473.html?guccounter=1&guce_referrer=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS8&guce_referrer_sig=AQAAACwGooJJKifSMQikC5_syBbVha6GC6nn0YKF5iO8lsDuzizOmkX-LPEwm_UA7sKrePCWLsCzSzr-OihZvB1nGixPtBTlnchx16uhEXgoEqYrOP5b90RcNHB8B-pMYUFezdJdbEgyOpEVnbUoAlpASg9N2CJ08NuH_n748a0DYVh9)** **\| [QuéPasa \[ES\]](https://quepasamedia.com/noticias/vida-y-estilo/tecnologia/la-avalancha-de-articulos-puede-socavar-la-confianza-en-la-ciencia-alerta-un-estudio/)** **\| [MSN](https://www.msn.com/es-us/noticias/mundo/la-avalancha-de-art%C3%ADculos-puede-socavar-la-confianza-en-la-ciencia-alerta-un-estudio/ar-AA1jkwlO)\|[\[ES\]](https://www.msn.com/es-us/noticias/mundo/la-avalancha-de-art%C3%ADculos-puede-socavar-la-confianza-en-la-ciencia-alerta-un-estudio/ar-AA1jkwlO)[News ES Euro \[ES\]](https://news.eseuro.com/internacional/2504702.html) \| [HM TV \[ES\]](https://hmtv.com.do/index.php/noticias/noticias/32689-la-avalancha-de-articulos-puede-socavar-la-confianza-en-la-ciencia-alerta-un-estudio) \| [BellerDigital \[ES\]](https://bellerdigital.net/archivos/91387)** **\|** [**Copiroyal \[ES\]**](https://www.copiroyal.com/en/la-avalancha-de-articulos-puede-socavar-la-confianza-en-la-ciencia-alerta-un-estudio/) **\| [Minuto 30 \[ES\]](https://www.minuto30.com/la-avalancha-de-articulos-puede-socavar-la-confianza-en-la-ciencia-alerta-un-estudio/1518601/) \| [Portal Político TV \[ES\]](https://www.portalpolitico.tv/ciencia-y-tecnologia/la-avalancha-de-articulos-puede-socavar-la-confianza-en-la-ciencia-alerta-un) \|** [**Canalpaís américa \[ES\]**](https://www.canalpais.com/ultimo-minuto-agencias-efe/2023/11/03/la-avalancha-de-articulos-puede-socavar-la-confianza-en-la-ciencia-alerta-un-estudio.html) **\| [El Periódico de México \[ES\]](https://elperiodicodemexico.com/nota.php?sec=Culturales&id=1030719) \| [CubaSí \[ES\]](https://cubasi.cu/es/noticia/la-avalancha-de-articulos-puede-socavar-la-confianza-en-la-ciencia-alerta-un-estudio) \| [El Nacional \[ES\]](https://www.elnacional.com/ciencia-y-tecnologia/la-avalancha-de-articulos-puede-socavar-la-confianza-en-la-ciencia/) \| [El Diario](https://www.eldiario.es/tecnologia/avalancha-articulos-socavar-confianza-ciencia-alerta-estudio_1_10654678.html) \| [ABC Paraguay \[ES\]](https://www.abc.com.py/ciencia/2023/11/03/la-avalancha-de-articulos-puede-socavar-la-confianza-en-la-ciencia-alerta-un-estudio/) \| [Listin Diario \[ES\]](https://listindiario.com/las-mundiales/20231104/avalancha-articulos-socavar-confianza-ciencia-alerta-estudio_781263.html)**: *La "avalancha" de artículos puede socavar la confianza en la ciencia, alerta un estudio*

### Catalan

-   [**3CAT \[Cat\]**](https://www.ccma.cat/324/alerten-duna-allau-darticles-cientifics-que-es-publiquen-sense-revisar-ne-la-qualitat/noticia/3259015/): *Alerten d'una "allau" d'articles científics que es publiquen sense revisar-ne la qualitat*

### Dutch

-   [**NRC \[NL\]**](https://www.nrc.nl/nieuws/2023/10/07/2800000-a4176187) - *2.800.000*

### German

-   [**LaborJournal \[DE\]**](https://www.laborjournal.de/editorials/2881.php) - *Sonderausgaben -- Fluch oder Segen?*

### Arabic

-   [**Hespress \[Morocco\]**](https://www.hespress.com/ندوة-علمية-تحذر-من-المنشورات-المزيفة-1270627.html)

### Romanian

-   [**HotNews.ro \[RO\]**](https://www.hotnews.ro/stiri-opinii-26732423-cine-plateste-publicarea-rezultatelor-cercetarii.htm)

### Norwegian

-   [**Forskning.no \[NO\]**](https://www.forskning.no/forskningsmetode-om-forskning/det-har-blitt-50-prosent-mer-forskning-pa-sju-ar-drukner-de-viktige-funnene/2281883) - also translated in English in their [sciencenorway English-language website](https://www.sciencenorway.no/research-research-communication/the-amount-of-research-in-the-last-seven-years-has-grown-by-50-per-cent-are-important-findings-being-overlooked/2288899)

### Swahili

-   [**Lango La Habar \[Tanzania\]**](https://www.langolahabari.com/2024/01/udsm-yaja-na-vipaumbele-kuimarisha.html)

### Vietnamese

-   [**Thanh Niên \[Vietnam\]**](https://thanhnien.vn/truong-dh-canh-bao-nha-khoa-hoc-tim-cach-ne-tap-chi-san-moi-185231207234643626.htm)

### Indonesian

-   [**The Conversation \[Indonesia\]**](https://theconversation.com/pelanggaran-akademis-di-indonesia-masih-marak-merusak-ekosistem-riset-dan-menyalahgunakan-uang-rakyat-224516)

# Blogs

-   [**In the Dark \[EN\]**](https://telescoper.blog/2023/09/29/the-strain-on-scientific-publishing/) -- the blog of astrophysicits [Peter Coles](https://www.facebook.com/TelescoperPage/?ref=embed_page)
-   [**Bishop Blog \[EN\]**](http://deevybee.blogspot.com/2023/10/spitting-out-ai-gobbledegook-sandwich.html) - the blog of [Dorothy Bishop](https://www.psy.ox.ac.uk/people/dorothy-bishop). Also:
    -   [here](http://deevybee.blogspot.com/2023/11/defence-against-dark-arts-proposal-for.html) when discussing her brilliant Defense Against the Dark Art course proposal
    -   [here](https://deevybee.blogspot.com/2024/02/the-world-of-poor-things-at-mdpi.html) when discussing issues with a series of papers at MDPI
-   [**Revues et Integrité \[FR\]**](https://www.redactionmedicale.fr/2023/10/le-miracle-des-numeros-speciaux-des-revues-scientifiques-consequence-de-la-mediocrite-de-certains-milieux-academiques-fait-le-bonheur-de-marchands-de-reves#) -- the blog of [Hervé Maisonneuve](https://www.redactionmedicale.fr/about)
-   [**The Blot Report \[EN\]**](https://blotreport.com/2023/09/30/thematic-sets-of-scientific-papers/)
-   [**Weekend list of Retraction Watch \[EN\]**](https://retractionwatch.com/2023/10/07/weekend-reads-the-strain-on-publishing-gino-defends-herself-the-rise-of-fake-peer-review-retractions/) - 7/10/2023
-   [**Digital Koans \[EN\]**](https://digital-scholarship.org/digitalkoans/2023/10/09/the-strain-on-scientific-publishing/) - Blog of Digital Scholarship
-   [**LSE Impact blog \[EN\]**](https://blogs.lse.ac.uk/impactofsocialsciences/2023/10/23/the-strain-on-academic-publishing/) -- a Social Science impact Blog from the London School of Economics
-   [**Scholarly Kitchen \[EN\]**](https://scholarlykitchen.sspnet.org/2023/10/30/quantifying-consolidation-in-the-scholarly-journals-market/) - an article about consolidation in the publishing market cites us for reference
-   [**Scholarly Kitchen \[EN\]**](https://scholarlykitchen.sspnet.org/2023/11/02/we-need-more-garbage-subtraction-because-of-ai) - an article about he rise of AI and the future of scientific publications
-   [**The Brief \[EN\]**](https://www.ce-strategy.com/the-brief/strategic-combination/) - monthly newsletter about scientific publishing by Clarke & Esposito talks about our paper in their "briefly noted" section
-   [**Reasonable people \[EN\]**](https://tomstafford.substack.com/p/a-new-study-puts-another-nail-in?utm_source=profile&utm_medium=reader2) - the substack blog of Tom Stafford
-   [**Nanoscale views \[EN\]**](http://nanoscale.blogspot.com/2023/11/scientific-publishing-where-are-we-going.html) - the physics blog of Douglas Natelson
-   [**Giuseppe Vizzari's blog \[EN\]**](https://giuseppevizzari.github.io/posts/2023/11/Contributing/) - Contributing to the public goods game...
-   [**/USR/SPACE \[EN\]**](https://www.mrowe.co.za/blog/2023/11/link-the-strain-on-scientific-publishing/) - Michael Rowe's blog
-   [**Daily Nous \[EN\]**](https://dailynous.com/2024/02/06/philosophers-should-you-pay-to-publish-your-paper-guest-post/) - Philosophers, Should You Pay to Publish Your Paper? by Justin Weinberg
-   [**Frontiers' Science News \[EN\]**](https://www.frontiersin.org/news/2024/02/21/bad-bibliometrics-dont-add-up-for-research-or-why-research-publishing-policy) - *Bad bibliometrics don't add up for research or why research publishing policy needs sound science*. This is a very critical piece. We explain why it's incorrect and faulty in [**our reply here**](https://the-strain-on-scientific-publishing.github.io/website/posts/response_to_frontiers/).
-   [**LSE Impact Blog \[EN\]**](https://blogs.lse.ac.uk/impactofsocialsciences/2024/04/29/academia-can-no-longer-ignore-its-systemic-inter-generational-inequality/) - Academia can no longer ignore its systemic inter-generational inequality
-   [**Federation of European Biochemical Societies Network \[EN\]**](https://network.febs.org/posts/beyond-the-journal-the-future-of-scientific-publishing/) - Beyond the journal: The future of scientific publishing

# Online magazines

-   [**ROARS \[IT\]**](https://www.roars.it/la-pressione-per-pubblicare-e-le-crepe-delleditoria-scientifica/) - the Returns on Academic Research and School website interviewed Paolo on the preprint.
-   [**The Meta News \[FR\]**](https://themeta.news/bourdieu-ou-shakespeare/) - access restricted to researchers in French universities and Research Institutes
-   [**SciELO en perspectiva \[PT\]**](https://blog.scielo.org/blog/2023/11/29/a-comunidade-cientifica-esta-publicando-muito-mais-e-isso-e-um-problema/?utm_source=rss&utm_medium=rss&utm_campaign=a-comunidade-cientifica-esta-publicando-muito-mais-e-isso-e-um-problema) - Portuguese blog hosting an article by Lilan Nassi-Calo
