---
title: "Media related to our project"
---

# Radio & Podcasts

- **Mark** was interviewed by Jonny Coates for the [Preprints in Motion podcast](https://open.spotify.com/episode/7vlhWvJs4puHo5iRkpe5X8?si=3EoxNVk0TEK3COvA-p-Sdw)
-   **Mark, Pablo** and **Paolo** were interviewed on [Episode 7 of the Science of doing Science podcast](https://creators.spotify.com/pod/show/sinnopsis/episodes/Episode-7-The-Strain-on-Scientific-Publishing-with-by-Mark-A-Hanson--Pablo-Gmez-Barreiro-and-Paolo-Crosetto-e2sfmii) held by the University of Cyprus SinnoPSis team
-   **Mark** participated to the [Tech & Science Daily](https://play.acast.com/s/tech-science-daily) podcast run by the Evening Standard. [Listen to Mark here!](https://play.acast.com/s/tech-science-daily/tom-hanks-targeted-in-fake-ai-dental-plan-ad)
-   **Pablo** was interviewed live on Radio 5 \[Spanish\]. Listen here: [Ciencia con pies de barro](https://www.rtve.es/play/audios/a-hombros-de-gigantes/proliferacion-publicaciones-cientificas-ciencia-pies-barro/7006765/)
-   **Pablo** was interviewed by Cadena Ser \[Catalan/Spanish\]. Download section [here](https://github.com/the-strain-on-scientific-publishing/website/raw/main/audio/exces%20estudis.wav) (Github link)
-   **Pablo** participated in the "Fundación Margarita Salas" podcast discussing the scientific publishing current panorama: [Link](https://www.youtube.com/watch?v=RS7pcW3s3eU)

# Videos

-   **Paolo** made a video to summarise the study for the Open Science directorate of INRAE \[French\]. Here: [L'édition Scientifique sous pression - décryptage par paolo Crosetto](http://science-ouverte.inrae.fr/fr/actualites/video-ledition-scientifique-sous-pression-decryptage-de-paolo-crosetto-co-auteur-de)

-   **Dan** and **Mark** presented at the 384th CGHE webinar, and there is a [Youtube video](https://youtu.be/3cUSkNbYI08?si=x3LlOZvpJ8wib4Np) of the seminar.

<iframe width="560" height="315" src="https://www.youtube.com/embed/3cUSkNbYI08?si=x3LlOZvpJ8wib4Np" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen>

</iframe>

-   **Dan** presented our work in Tanzania, including [an interview in Swahili here](https://twitter.com/thechanzo/status/1752734519726080304?s=48&t=jSK1UrM52iUTsyV5Rqbg9Q). The full video of the nearly 2-hour long event, in English with some Swahili, [is here on Youtube](https://youtu.be/IwSF0eLg44w?si=jQTg9yqY44TnoPq0) (and below)

<iframe width="560" height="315" src="https://www.youtube.com/embed/IwSF0eLg44w?si=jQTg9yqY44TnoPq0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen>

</iframe>

-   **Dan** interviewed by the Tanzanian channel [**Mlimani TV \[in Swahili\]**](https://youtu.be/CNcSDSdWCfA?si=5_iT6KY4wUrM3mpN)

<iframe width="560" height="315" src="https://www.youtube.com/embed/CNcSDSdWCfA?si=mgAhpguFgzpUdlx3" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen>

</iframe>

-   **Paolo** presented our work *in Italian* in Milan, at an Open Science conference held at the headquarters of UniMi in September 2013. The [webpage of the event is here](https://openscience.unimi.it/ciclo-di-incontri-sulla-comunicazione-scientifica/); and here you find [**the full video of the conference**](https://garr.tv/w/7dj2iHjQHUXK18Kiwk6gXB), including introduction by the Dean of the University of Milan Elio Franzini and by the philosopher Haikel Hosni.

# Others

[**Viaje al lado oscuro de la ciencia** \[Spanish\]](Slides/pArAdigmA.pdf) - Building on "The Strain" paper, this is a brief comment on all things wrong affecting the current scientific publishing panorama. Published in Malaga´s University magazine, [**pArAdigmA**](https://riuma.uma.es/xmlui/handle/10630/23) (volúmen 26, 2024).
